name: Get Posts # Action的名字
on: # 触发条件
  push: # push操作
    branches: [ master ] # 当有新push到master分支时运行
jobs: # 作业
  getPost: # 一个名为“获得文章”的作业
    runs-on: ubuntu-latest # 在最新版的Ubuntu系统下运行
    steps: # 作业步骤
      - name: Checkout # 将仓库内master分支的内容下载到工作目录
        uses: actions/checkout@v3 # 脚本来自 https://github.com/actions/checkout
      - name: Get Post # 获得文章
        run: |
          echo Hello, world!
      - name: Run a multi-line script # Runs a set of commands using the runners shell
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
